name: JSON Schema Validation

on:
  pull_request:
    # Activated only when changes are made to your /data/ folder
    paths:
      - 'public/data/**/*.json'
  workflow_dispatch: # Manual start option

permissions:
  contents: read
  # Add this if you want the bot to write comments in PR
  pull-requests: write

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Validate characters.json
        uses: GrantBirki/json-yaml-validate@v4.0.0
        with:
          # Path to the folder with your schemas
          json_schema: 'public/data/schemas/characters.schema.json'
          # List of file paths to validate. Each file path must be on a newline.
          files: 'public/data/characters.json'
          # Optional: comment in PR with results
          comment: 'true'

      - name: Validate details.json
        uses: GrantBirki/json-yaml-validate@v4.0.0
        with:
          json_schema: 'public/data/schemas/details.schema.json'
          files: 'public/datadetails.json'
          comment: 'true'
